// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as DBParser from "./lib/DBParser.mjs";

function App$Button(Props) {
  var onClick = Props.onClick;
  var children = Props.children;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var onClick$1 = onClick !== undefined ? onClick : (function (param) {
        
      });
  var className$1 = className + " w-8 h-8 group flex justify-center items-center rounded-md bg-blue-500 text-white text-sm font-medium cursor-pointer shadow-sm hover:bg-blue-400";
  return React.createElement("button", {
              className: className$1,
              onClick: onClick$1
            }, children);
}

var Button = {
  make: App$Button
};

function App(Props) {
  var match = React.useState(function () {
        return "";
      });
  var setState = match[1];
  var state = match[0];
  var onChange = function (e) {
    e.preventDefault();
    var value = e.target.value;
    Curry._1(setState, (function (_prev) {
            return value;
          }));
  };
  return React.createElement("div", undefined, React.createElement("textarea", {
                  className: "absolute right-0 top-0 bottom-0 left-0 outline-0 p-4",
                  placeholder: "Sheet music",
                  value: state,
                  onChange: onChange
                }), React.createElement("div", {
                  className: "flex absolute top-4 right-4"
                }, React.createElement(App$Button, {
                      onClick: (function (param) {
                          return Curry._1(setState, (function (_prev) {
                                        return DBParser.modifiedTone(state, "RisingTone");
                                      }));
                        }),
                      children: "+",
                      className: "mr-4"
                    }), React.createElement(App$Button, {
                      onClick: (function (param) {
                          return Curry._1(setState, (function (_prev) {
                                        return DBParser.modifiedTone(state, "FallingTone");
                                      }));
                        }),
                      children: "-"
                    })));
}

var make = App;

export {
  Button ,
  make ,
}
/* react Not a pure module */
